name: "Update component database"
on:
  push:
  pull_request:
  # schedule:
  #   - cron: '0 3 * * *'
jobs:
  build_and_update:
    name: "Update component database and frontend"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip nodejs npm wget zip unzip
          sudo pip3 install requests click
      - name: Build frontend
        run: |
          cd web
          if [ "$GITHUB_REPOSITORY" = 'yaqwsx/jlcparts-dev' ]; then
            export BASEURL=https://jlcparts-dev.honzamrazek.cz
          else
            export BASEURL=https://yaqwsx.github.io/jlcparts
          fi
          npm install --silent
          NODE_ENV=production PUBLIC_URL=${BASEURL} npm run build
          if [ $GITHUB_REPOSITORY = 'yaqwsx/jlcparts-dev' ]; then
            echo 'jlcparts-dev.honzamrazek.cz' > build/CNAME
          fi
      - name: Update database
        if: false
        run: |
          set -x
          # Show the outside IP address in log
          curl ifconfig.me
          sudo pip3 install -e .
          wget -q https://yaqwsx.github.io/jlcparts/data/cache.zip && unzip cache.zip
          wget --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" \
               -q -O parts.csv https://jlcpcb.com/componentSearch/uploadComponentInfo
          iconv -f GB18030// -t UTF-8//TRANSLIT parts.csv -o partsUtf8.csv

          jlcparts getlibrary --cache cache.json --age 20000 --newLogFile newComponents.txt partsUtf8.csv jlcdata.json
          cp jlcdata.json cache.json
          jlcparts buildtables jlcdata.json web/build/data
          zip web/build/data/cache.zip cache.json
          # The cache feature is temporarily disabled as it is unusable
          # wget -q -O web/build/data/changelog.json https://yaqwsx.github.io/jlcparts/data/changelog.json
          # jlcparts updatechangelog newComponents.txt web/build/data/changelog.json
      - name: Tar artifact # Artifact are case insensitive, this is workaround
        run: tar -czf web_build.tar.gz web/build/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: web_build
          path: web_build.tar.gz
          retention-days: 14
  deploy:
    name: "Deploy"
    runs-on: ubuntu-20.04
    needs: build_and_update
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout # Required for GH-pages deployment
        uses: actions/checkout@v2
      - name: "Download web"
        uses: actions/download-artifact@v2
        with:
          name: web_build
      - name: Untar artifact
        run: tar -xzf web_build.tar.gz
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: web/build
          single-commit: true
